### DISCUSSION TITLE
What's the values override magic needed to set up DHCP?

### DISCUSSION THREAD

**Discussion by kaitlinsm** [MoJo2600/pihole-kubernetes#145] [Q&A] [answered]
I'm probably going to kick myself once I figure it out, but I'm a bit stumped as to how to set up the values overrides so that I can have Pihole be my DHCP server.

I thought that since DHCP is network broadcast... thing, it can't work with a k8s Service, so my values.yaml override looks like this:

```
# must run the DHCP server on the host network for broadcasting
hostNetwork: true

serviceWeb:
  # an ingress rule configured elsewhere serves this service
  type: ClusterIP

serviceDns: 
  # 192.168.0.5 is the IP address of the k8s host (as in, bare metal)
  # 192.168.0.6 is an IP address that MetalLB is allowed to use
  loadBalancerIP: 192.168.0.6
  annotations:
    metallb.universe.tf/allow-shared-ip: server-load-balancer
  type: LoadBalancer
  externalTrafficPolicy: Local
```

 When I do this, the pihole image errors with 
 ```
dnsmasq: failed to create listening socket for port 53: Address already in use
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1. 
```

and then the container shuts down.

I'm stumped. Lil' help?

- k
