### DISCUSSION TITLE
Integrate Traefik2 for WebUI

### DISCUSSION THREAD

**Discussion by goacid** [MoJo2600/pihole-kubernetes#157] [Ideas]
Something like that could be integrated to templates ?
```

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ir-pi-80
  namespace: pihole
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`pi.holet`)
    kind: Rule
    services:
    - name: pihole-svc-http
      port: 80
```
