### DISCUSSION TITLE
All LoadBalancer External IP's are Pending

### DISCUSSION THREAD

**Discussion by ccordero5500** [MoJo2600/pihole-kubernetes#166] [Q&A]
I can't seem to get an external IP for any pihole services in k8s even though I have traefik and metallb installed.  I'm getting the following error.

```
$ kubectl describe service/pihole-web -n pihole
Name:                     pihole-web
Namespace:                pihole
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-2.0.0
                          heritage=Helm
                          release=pihole
Annotations:              meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: pihole
                          metallb.universe.tf/allow-shared-ip: pihole-svc
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.17.88
IPs:                      10.99.17.88
IP:                       192.168.0.64
Port:                     http  8080/TCP
TargetPort:               http/TCP
NodePort:                 http  31251/TCP
Endpoints:                10.244.1.20:80
Port:                     https  8443/TCP
TargetPort:               https/TCP
NodePort:                 https  30890/TCP
Endpoints:                10.244.1.20:443
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31296
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  AllocationFailed  97s   metallb-controller  Failed to allocate IP for "pihole/pihole-web": can't change sharing key for "pihole/pihole-web", address also in use by kube-system/traefik: existing service does not allow sharing
```

My helm chart values are the following.

```
serviceWeb:
  loadBalancerIP: 192.168.0.64
  http:
    port: 8080
  https:
    port: 8443
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.0.64
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
adminPassword: NotMyRealPassword
```
