### DISCUSSION TITLE
Adding pihole via argocd

### DISCUSSION THREAD

**Discussion by auxworker** [MoJo2600/pihole-kubernetes#249] [Show and tell]
Hi

I have been adding applications into my k3s environment using Argocd, as such, it seems adding every new helm chart into argocd is its own journey. Here is a recipe that works for me.

https://github.com/auxworker/thoughts/blob/main/argocd-pihole-plain.yaml

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-pihole
  namespace: argocd
spec:
  project: default
  source:
    path: charts/pihole
    repoURL: https://github.com/MoJo2600/pihole-kubernetes
    targetRevision: bfc0351af6501b19f84a5f08514bdc0b887f3703 #using version number 2.11.0 kept returning errors but I was able to use git commit hash instead
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
```

I noticed unlike the other open source helm charts, I could not use 2.11.0 in targetRevision. I checked the  `charts/pihole)/Chart.yaml` file and the version looked fine, not sure why argocd had issues with it, but either way, entering the hash commit , and it picks up on the correct version number.

Hope this helps.

**Comment by KGB33** [comment]
Thanks for the great starting point! I modified it a bit so Argo would use the helm chart instead of the git repository. Which makes it easier for me to set some of the variables - while still getting the same end result. 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
spec:
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: "2.14.0"
      chart: pihole
      helm:
        releaseName: pihole
        valueFiles: 
          - $values/k8s-apps/pihole/values.yaml
    - repoURL: https://github.com/KGB33/homelab.git
      ref: values
      targetRevision: HEAD
      path: k8s-apps/pihole/
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

Also I noticed that the `targetRevison` on the helm charts uses just the version number (`x.y.z`) whereas the git tags were prefixed with "pihole" (i.e. `pihole-x.y.z`).
