### DISCUSSION TITLE
Pihole, ingress and subpath, how?!

### DISCUSSION THREAD

**Discussion by i5Js** [MoJo2600/pihole-kubernetes#253] [Q&A] [answered]
I have the pihole working fine, but I would like to integrate it into a local domain with some services. ex:

domain.k3s.local/longhorn -> longhorn ui
domain.k3s.loca/pihole -> pihole.

But I having issues with the ingress, because, although http://domain.k3s.local/pihole/admin/ works fine, and I get the credential ui, when I type the password, it redirects to http://domain.k3s.local/admin/ and of course it fails. Below you can see my ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: pihole
    meta.helm.sh/release-namespace: dns-home
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_hide_header X-Frame-Options;
      rewrite ^/pihole/?$ /pihole/admin break;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  creationTimestamp: "2023-02-16T13:22:59Z"
  generation: 7
  labels:
    app: pihole
    app.kubernetes.io/managed-by: Helm
    chart: pihole-2.11.1
    heritage: Helm
    release: pihole
  name: pihole
  namespace: dns-home
  resourceVersion: "2012116"
  uid: 3c4cefff-4cf1-447c-b3e3-05f568bb8601
spec:
  ingressClassName: nginx
  rules:
  - host: myhome.k3s.local
    http:
      paths:
      - backend:
          service:
            name: pihole-web
            port:
              name: http
        path: /pihole(/|$)(.*)
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.122
```

Any idea?

Thanks, all.

**Comment by dwarf-king-hreidmar** [comment]
Have you tried setting this value: https://github.com/MoJo2600/pihole-kubernetes/blob/4025abe82a5f7a0aeb7802300b50ec018d3ca23b/charts/pihole/values.yaml#L146 to `/pihole` ? 

I think then when you login the pihole app will append `/pihole` to your path before admin

If that doesn't work: 
Do you have anything against using subdomains instead? If not this gets a little easier and I have some examples with haproxy if you'd like them.

**Comment by i5Js** [comment]
Hey, thanks for your answer. Yes, I did, but it didn't work. With subdomains works fine, I had it in other installation, but my goal is having somthing similar to: 
myhome.local/longhorn
myhome.local/pihole
myhome.local/graphana

etc.

**Reply by dwarf-king-hreidmar** [reply]
Do you still need rewrite rules if you change that path?  Have you checked if the default path of the app actually changes?

**Reply by dwarf-king-hreidmar** [reply]
I would expect this to work like: you set up base path in nginx that goes to your upstream server (in this case correctly labled pods). 

Once you reach your app if it properly passes path it would always send $URL/$BASEPATH/$PATH back to your browser.. no nginx rewrite needed but maybe I'm mistaken

**Reply by dwarf-king-hreidmar** [reply]
Now that I'm looking at this closer this sets the path in ingress not in the app. If we could do that was supported it would be cleaner .. let me look around a bit

**Comment by i5Js** [comment]
This is my actual ingress... still redirecting to /admin/ if it helps:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: dns-home
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-no-cache: "1"
    nginx.ingress.kubernetes.io/proxy-set-header: Authorization $http_authorization;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~ ^/pihole/?$) {
        return 301 /pihole/admin;
      }
  labels:
    app: pihole
spec:
  ingressClassName: nginx
  rules:
  - host: myhome.k3s.local
    http:
      paths:
      - path: /pihole(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: pihole-web 
            port:
              name: http
      - path: /pihole
        pathType: Prefix
        backend:
          service:
            name: pihole-web 
            port:
              name: http
```
