### DISCUSSION TITLE
Ingress + Metallb - how to access domain

### DISCUSSION THREAD

**Discussion by andeke07** [MoJo2600/pihole-kubernetes#265] [Q&A]
I am a little new to Kubernetes so apologies if this is basic but hoping someone can help. I have recently been playing around with this Helm chart and have gotten everything working. 

My setup: 
- 3x nodes: 192.168.0.11, 12, 13
- Metallb set up to dish out IPs on 192.168.0.2-10

I followed the documentation on here and a few other bits I found online. My DNS is responding on 192.168.0.2 and I can also access the web ui on http://192.168.0.2/admin. So far so good!

My question comes to setting up the ingress available in the Helm chart. I have the following:

```yaml
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: public
    kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
  - dns.my.domain
  path: /
  tls:
  - hosts:
    - dns.my.domain
    secretName: pihole-web-tls
```

So if I set my DNS up to point dns.my.domain to one of my nodes (say 192.168.0.11) this works well - I can access https://dns.my.domain/admin and I get my generated SSL certificate securing it. 

However, if I instead point dns.my.domain to 192.168.0.2, I cannot access the web UI. 

So it seems if I point my DNS to one of the nodes, this all works fine (but this means that it is pointed at a single node which sort of defeats the purpose in my mind of a distributed cluster), should I be able to point my DNS to the IP of my LoadBalancer address (192.168.0.2) and get the same behaviour? Or is there some other config I am missing? Do I need a load balancer external to my Kubernetes cluster for this sort of workflow to work?
