### ISSUE TITLE
Fresh install of pihole latest helmchart - webui returns error 503

### ISSUE THREAD

**Issue by lord-kyron** [MoJo2600/pihole-kubernetes#158]
Hi all,
I've made a fresh install fo the chart with doh enabled. I've also enabled the ingress service and used custom port for the webHttp. However - my setup is a bit complicated. Here is how I am accessing it:
nginx reverse proxy running on the k8s node (as I am using my host not only for k8s) -> k3s kubernetes cluster with nginx ingress controller -> pihole web http service -> pihole pod
However, my setup before the actual pod seems working. The problem seems to. be something with the pihole webui itself or with the php socket, as I am actually getting to the lighthttpd server on the pihole pod, but then the lighthttpd returns me error 503 and in the logs I can see the following:
`unlink /var/run/lighttpd/php.socket-0 after connect failed: Connection refused`

Can you please, suggest what it can be and if the problem is my setup or?
Thanks!

**Comment by lord-kyron** [comment]
Some have simmilar issues or it is just me?

**Comment by Federkun** [comment]
I installed the latest chart from scratch 30m ago, and it was all good for me. (using `pihole/pihole:5.8.1`)

**Comment by MoJo2600** [comment]
I did a clean reinstall on my cluster and everything was working.

**Comment by lord-kyron** [comment]
I am still getting this. It seems some problem with lighttpd and php-cgi but I cannot get why it is happening.
The erro which I see in lighttpd error.log on the pod is:
```
(mod_fastcgi.c.3580) child signaled: 7
unlink /var/run/lighttpd/php.socket-0 after connect failed: Connection refused
```
And this is repeating and pod is failing and rebooting. Tried both "latest", "v5.8.1-stretch", "v5.8.1-buster" and "v5.8-stretch" image tags - always failing with the same.

**Comment by lord-kyron** [comment]
Here is the full log from the pihole pod:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.                                                 
[s6-init] ensuring user provided files have correct perms...exited 0.                                                         
[fix-attrs.d] applying ownership & permissions fixes...                                                                       
[fix-attrs.d] 01-resolver-resolv: applying...                                                                                 
[fix-attrs.d] 01-resolver-resolv: exited 0.                                                                                   
[fix-attrs.d] done.                                                                                                           
[cont-init.d] executing container initialization scripts...                                                                   
[cont-init.d] 20-start.sh: executing...                                                                                       
 ::: Starting docker specific checks & setup for docker pihole/pihole                                                         
  [i] Installing configs from /etc/.pihole...                                                                                 
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!                                                 
  [i] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf...  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
Converting DNS1 to PIHOLE_DNS_                                                                                                
Converting DNS2 to PIHOLE_DNS_                                                                                                
Setting DNS servers based on PIHOLE_DNS_ variable                                                                             
Custom WEB_PORT set to 8095                                                                                                   
INFO: Without proper router DNAT forwarding to 0.0.0.0:8095, you may not get any blocked websites on ads                      
::: Pre existing WEBPASSWORD found                                                                                            
DNSMasq binding to default interface: eth0                                                                                    
Added ENV to php:                                                                                                             
            "PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",                                                                 
            "ServerIP" => "0.0.0.0",                                                                                          
            "VIRTUAL_HOST" => "pi.hole",                                                                                      
Using IPv4 and IPv6                                                                                                           
::: Preexisting ad list /etc/pihole/adlists.list detected ((exiting setup_blocklists early))                                  
::: Testing pihole-FTL DNS: [cont-init.d] 20-start.sh: exited 1.                                                              
[cont-finish.d] executing container finish scripts...                                                                         
[cont-finish.d] done.                                                                                                         
[s6-finish] waiting for services.                                                                                             
[s6-finish] sending all processes the TERM signal.                                                                            
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by lord-kyron** [comment]
Here is my config of values.yaml file:
```
replicaCount: 1

strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 1

image:
  repository: "pihole/pihole"
  tag: v5.8.1
  pullPolicy: IfNotPresent

dnsHostPort:
  enabled: false
  port: 53

serviceDns:
  type: NodePort
  port: 53
  externalTrafficPolicy: Local
  loadBalancerIP: ""
    # a fixed LoadBalancer IP
  annotations: {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: pihole-svc

serviceWeb:
  http:
    enabled: true
    port: 80
  https:
    enabled: true
    port: 443
  type: ClusterIP
  externalTrafficPolicy: Local
  loadBalancerIP: ""
    # a fixed LoadBalancer IP
  annotations: {}
    # metallb.universe.tf/address-pool: network-services
    # metallb.universe.tf/allow-shared-ip: pihole-svc

virtualHost: pi.hole

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    # virtualHost (default value is pi.hole) will be appended to the hosts
    - example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #     #- virtualHost (default value is pi.hole) will be appended to the hosts
  #      - chart-example.local

# Probes configuration
probes:
  # probes.liveness -- Configure the healthcheck for the ingress controller
  liveness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 2
  #  memory: 1Gi

persistentVolumeClaim:
  # set to true to use pvc
  enabled: true
  # set to true to use you own pvc
  # existingClaim: myExistingClaim
  annotations: {}

  accessModes:
    - ReadWriteOnce
  size: "200Mi"
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
  ## This is especially handy for volume plugins that don't natively support sub mounting (like glusterfs).

  ## subPath: "pihole"

nodeSelector: {}

tolerations: []

affinity: {}

# Administrator password when not using an existing secret (see below)
adminPassword: "admin"

# Use an existing secret for the admin password.
admin:
  existingSecret: ""
  passwordKey: "password"

# extraEnvironmentVars is a list of extra enviroment variables to set for pihole to use
extraEnvVars: {}
  # TZ: UTC

# extraEnvVarsSecret is a list of secrets to load in as environment variables.
extraEnvVarsSecret: {}
  # env_var:
  #   name: secret-name
  #   key: secret-key

# default upstream DNS servers to use
DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

antiaff:
  # set to true to enable antiaffinity (example: 2 pihole DNS in the same cluster)
  enabled: false
  # Here you can set the pihole release (you set in `helm install <releasename> ...`)
  # you want to avoid
  avoidRelease: pihole1
  # Here you can choose between preferred or required
  strict: true

doh:
  # set to true to enabled DNS over HTTPs via cloudflared
  enabled: false
  name: "cloudflared"
  repository: "crazymax/cloudflared"
  tag: latest
  pullPolicy: Always
  envVars: {}
    # Here you can pass environment variables to the DoH container, for example:
    # TUNNEL_DNS_UPSTREAM: "https://1.1.1.2/dns-query,https://1.0.0.2/dns-query"

  # Probes configuration
  probes:
    # probes.liveness -- Configure the healthcheck for the doh container
    liveness:
      enabled: true
      initialDelaySeconds: 60
      failureThreshold: 10
      timeoutSeconds: 5

dnsmasq:
  upstreamServers: []
  # Here you can add upstream dns servers with. All lines will be added to the
  # pihole dnsmasq configuration.
  # The format should be like:
  # - server=/foo.bar/192.168.178.10
  # - server=/bar.foo/192.168.178.11

  customDnsEntries: []
  # Here you can add custom dns entries to override the
  # dns resolution with. All lines will be added to the
  # pihole dnsmasq configuration.
  # The format should be like:
  # - address=/foo.bar/192.168.178.10
  # - address=/bar.foo/192.168.178.11

  additionalHostsEntries: []
  # Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
  # - 192.168.0.3     host4
  # - 192.168.0.4     host5

  staticDhcpEntries: []
  # Static DHCP config
  # staticDhcpEntries:
  # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME

adlists: {}
  # If you want to provide blocklists, add them here.
  # - https://hosts-file.net/grm.txt
  # - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

whitelist: {}
  # If you want to provide whitelisted domains, add them here.
  # - clients4.google.com

blacklist: {}
  # If you want to have special domains blacklisted, add them here
  # - *.blackist.com

regex: {}
  # Add regular expression blacklist items
  # - (^|\.)facebook\.com$

ftl: {}
  # Add values for pihole-FTL.conf
  # MAXDBDAYS: 14

webHttp: "80"
webHttps: "443"
hostNetwork: "false"
privileged: "false"

customVolumes:
  enabled: false
  config: {}
    # any volume type can be used here
    # hostPath:
    #   path: "/mnt/data"

monitoring:
  podMonitor:
    enabled: false
  sidecar:
    enabled: false
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: 0.0.10
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi
```
Do I have to run it on privileged mode or something? Still couldn't get what is going on. I don't have problems with any other charts or services.

**Comment by MoJo2600** [comment]
I tried the latest Chart version with your `values.yml`:

Startup Logs
```bash
kubectl logs -f pihole-79dc788bc8-m99jc 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-resolver-resolv: applying... 
[fix-attrs.d] 01-resolver-resolv: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 20-start.sh: executing... 
 ::: Starting docker specific checks & setup for docker pihole/pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf
Converting DNS1 to PIHOLE_DNS_
Converting DNS2 to PIHOLE_DNS_
Setting DNS servers based on PIHOLE_DNS_ variable
  [✓] New password set
DNSMasq binding to default interface: eth0
Added ENV to php:
			"PHP_ERROR_LOG" => "/var/log/lighttpd/error.log",
			"ServerIP" => "0.0.0.0",
			"VIRTUAL_HOST" => "pi.hole",
Using IPv4 and IPv6
::: setup_blocklists now setting default blocklists up: 
::: TIP: Use a docker volume for /etc/pihole/adlists.list if you want to customize for first boot
::: Blocklists (/etc/pihole/adlists.list) now set to:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
::: Testing pihole-FTL DNS: FTL started!
::: Testing lighttpd config: Syntax OK
::: All config checks passed, cleared for startup ...
::: Enabling Query Logging
  [i] Enabling logging...
  [✓] Logging has been enabled!
 ::: Docker start setup complete
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)
[cont-init.d] 20-start.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting crond
Starting lighttpd
Starting pihole-FTL (no-daemon) as root
[services.d] done.
```
If I try to access the pod with a port forward `kubectl port-forward pihole-79dc788bc8-m99jc 8087:80` the pihole UI is accessible:

`curl http://localhost:8087`

```html
    <!doctype html>
    <html lang='en'>
        <head>
            <meta charset='utf-8'>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>● localhost</title>
            <link rel='stylesheet' href='pihole/blockingpage.css'>
            <link rel='shortcut icon' href='admin/img/favicons/favicon.ico' type='image/x-icon'>
        </head>
        <body id='splashpage'>
            <div id="pihole_card">
              <img src='admin/img/logo.svg' alt='Pi-hole logo' id="pihole_logo_splash" />
              <p>Pi-<strong>hole</strong>: Your black hole for Internet advertisements</p>
              <a href='/admin'>Did you mean to go to the admin panel?</a>
            </div>
        </body>
    </html>
```

I'm sorry. But it works on my machine :( Maybe there is an issue with the wrong architecture of the docker image? I'm on x86 so not sure if my cluster can be compared with yours?

**Comment by lord-kyron** [comment]
I am using k3s kubernetes cluster running on single node Ubuntu 20.04 server, but according to pihole image tags, the image should autodiscover the required architecture. However - I will now try with amd64 tag images to check what you suggest.

**Comment by lord-kyron** [comment]
@MoJo2600  - can you explain what is the difference between those:
```
serviceWeb:
              http:
                enabled: true
                port: 80
              https:
                enabled: true
                port: 443
```
and 
```
    webHttp: "80"
    webHttps: "443"
```

Also - in general I find the readme file to lack information about what is what in the config. I can the values described to what is the default of each one, but what is the purpose of each one is a bit confusing without explanation.
Thanks!
