### ISSUE TITLE
Error installing 2.0.0 with helm

### ISSUE THREAD

**Issue by netnutmike** [MoJo2600/pihole-kubernetes#168]
Hi, let me start out saying I am very new to using helm.  I am trying to install the 2.0.0 release with using a load balancer.  I do have the 1.7.6 version running per Jeff's video.

Here is my values file I created:

```
---
serviceWeb:
  loadBalancerIP: '10.232.1.153'
  type: LoadBalancer

serviceDns:
  loadBalancerIP: '10.232.1.153'
  type: LoadBalancer

serviceDhcp:
  enabled: false

ingress:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 256Mi

persistentVolumeClaim:
  enabled: true
```

This is the error I get:

```
helm install --version '2.0.0' --namespace pihole --values pihole.yaml pihole mojo2600/pihole
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

I have a couple of questions based on the 1.7.6 version.  I cannot see how to set the timezone or ntp or current time.  

Also, I noticed that all requests seem to be coming from a node ip address and not the real client address.

Thank you for your patience around my lack of knowledge of helm.

Mike
