### ISSUE TITLE
Getting a weird scheduling error

### ISSUE THREAD

**Issue by bab014** [MoJo2600/pihole-kubernetes#180]
### Related to the TCP pods being generated
Status 
```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-25T01:19:21Z"
    message: '0/3 nodes are available: 1 node(s) didn''t have free ports for the requested
      pod ports, 2 node(s) didn''t match Pod''s node affinity/selector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
```

### I was following @geerlingguy tutorial for hosting on a raspberry pi using a helm chart. Everything works fine except the TCP pods.

My values.yaml
```yaml
---
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
serviceTCP:
  loadBalancerIP: ''###.###.#.##'
  type: LoadBalancer
serviceUDP:
  loadBalancerIP: '###.###.#.##'
  type: LoadBalancer
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
# If using in the real world, set up admin.existingSecret instead.
adminPassword: #########
```
### I used the IP of one of my worker nodes

I'm about as new to this stuff as you can be so I appreciate any help.
