### ISSUE TITLE
PiHole not handing out DHCP addresses

### ISSUE THREAD

**Issue by funkel1989** [MoJo2600/pihole-kubernetes#185]
I'm running a k3s cluster with one master node and one agent. All jobs currently running on a single agent and my master is tainted.

I am looking to use the DNS and DHCP functionality of the PiHole because my router/model will not allow me to distribute DNS servers.

I've set it up to deploy on hostNetwork and with privileged mode set to true, Pihole starts just fine but no devices can communicate with it on port 67 to obtain an ip address.

values file:

```yaml
---
dnsHostPort:
  enabled: true
  port: 53
serviceDns:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.210"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
serviceDhcp:
  enabled: true
  type: NodePort
serviceWeb:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.210"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole"
  annotations: {}
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
admin:
  existingSecret: "pihole-secret"
webHttp: "55480"
webHttps: "55443"
hostNetwork: "true"
privileged: "true"
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 8.8.8.8
extraEnvVars:
  TZ: "America/Detroit"
  ServerIP: 192.168.1.27 ## This is the node in the cluster that it will always load on
```

Some of the things I've tried:
1. Validated all of my firewalls on master and agent k3s node are disabled
2. Validated nothing else is consuming these ports that would break it.
3. attempted exposing dhcp through a load balancer, while this worked it made no difference in the ability to hand out IP addresses. Currently set to nodeport and still doesn't work.
4. unable to telnet to pod from external to cluster  or inside of the cluster on port 67. receive connection refused.

kubectl get services -n pihole shows :
```bash
NAME             TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
pihole-dhcp      NodePort       10.43.143.59   <none>          67:30244/UDP                 114s
pihole-dns-udp   LoadBalancer   10.43.153.81   192.168.1.210   53:32131/UDP                 114s
pihole-dns-tcp   LoadBalancer   10.43.137.22   192.168.1.210   53:30599/TCP                 114s
pihole-web       LoadBalancer   10.43.29.53    192.168.1.210   80:30192/TCP,443:31420/TCP   114s
```

kubectl describe service pihole-dhcp -n pihole shows:
```bash
Name:                     pihole-dhcp
Namespace:                pihole
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-2.2.1
                          heritage=Helm
                          release=pihole
Annotations:              field.cattle.io/publicEndpoints:
                            [{"addresses":["192.168.1.27"],"port":30244,"protocol":"UDP","serviceName":"pihole:pihole-dhcp","allNodes":true}]
                          meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: pihole
Selector:                 app=pihole,release=pihole
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.143.59
IPs:                      10.43.143.59
Port:                     client-udp  67/UDP
TargetPort:               client-udp/UDP
NodePort:                 client-udp  30244/UDP
Endpoints:                192.168.1.27:67
Session Affinity:         None
External Traffic Policy:  Local
Events:                   <none>
```

Any help or further idea's you could provide to get this working would be greatly appreciated. I am new to k3s and Kubernetes in general so sorry ahead of time if I've said anything noobish
