### ISSUE TITLE
dnsmasq not adding additionalHostsEntries

### ISSUE THREAD

**Issue by MujiSayed** [MoJo2600/pihole-kubernetes#191]
Hello, 
Not sure what i'm doing wrong, but pihole deploys successfully, but the following section doesn't seem to work. When i visit pihole, and click on local DNS -> DNS Records, this section is empty

```
dnsmasq:
  # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
  upstreamServers: []
  # - server=/foo.bar/192.168.178.10
  # - server=/bar.foo/192.168.178.11

  # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
  customDnsEntries: [
  # - address=/foo.bar/192.168.178.10
  # - address=/bar.foo/192.168.178.11

  ]
  # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
  additionalHostsEntries: [
    10.15.15.200    host1.iad
    10.15.15.201    host2.iad
    10.15.15.202    host3.iad
    10.15.15.210    host4.iad
    10.15.15.211    host5.iad
    10.15.15.15      host6.iad
    10.15.15.15      host7.iad
    10.15.15.15      host8.iad
]
```
Would appreciate any assistance please.
Thanks,

**Comment by simonosterberg** [comment]
Im not able to confirm it right now but i think you want to use the customDnsEntries and not additionalHostEntries for adding hosts to local DNS records.

**Comment by MujiSayed** [comment]
tried giving this a shot as well, but am still not seeing anything in the custom list

```
  customDnsEntries: [
  # - address=/foo.bar/192.168.178.10
  # - address=/bar.foo/192.168.178.11
  address=/host1.iad/10.15.15.200
  ]
```

also tried this but this resulted in the following error: Error: failed to parse pihole.values.yml: error converting YAML to JSON: yaml: line 264: did not find expected node content

```
  customDnsEntries: [
  # - address=/foo.bar/192.168.178.10
  # - address=/bar.foo/192.168.178.11
     - address=/host1.iad/10.15.15.200
  ]
```

**Comment by MoJo2600** [comment]
My custom dns look like this:

```
dnsmasq:
  customDnsEntries:
    - address=/share.xxx.de/192.168.178.10
    - address=/grafana.xxx.de/192.168.178.60
    - address=/pihole.xxx.de/192.168.178.252
    - address=/openhab.xxx.de/192.168.178.25
    - address=/odroid.xxx.de/192.168.178.26
    - address=/trac.xxx.de/192.168.178.64
  additionalHostsEntries:
    - 192.168.178.10    nas.foo.bar       nas
    - 192.168.178.60    unifi.foo.bar     unifi
    - 192.168.178.61    home.foo.bar      home
```
