### ISSUE TITLE
unable to schedule web containers

### ISSUE THREAD

**Issue by enuno** [MoJo2600/pihole-kubernetes#199]
When running: helm install --version '2.0.0' --namespace pihole --values pihole.yaml pihole mojo2600/pihole
I get this error:
2m21s       Warning   FailedScheduling        pod/svclb-pihole-web-lcj6p       0/5 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 4 node(s) didn't match Pod's node affinity/selector.

This is my pihole.yaml file:
---
persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 10.2.0.90
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 10.2.0.90
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDhcp:
  loadBalancerIP: 10.2.0.90
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

**Comment by MoJo2600** [comment]
Hi,

I strongly recomment to use the latest 2.5.3 version of this chart. 

None the less my values.yaml file looks not that much different from yours. Mine looks like this:
```
...
serviceWeb:
  loadBalancerIP: 192.168.178.252
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.178.252
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
...
```
can you maybe do a `kubectl describe pod YOURPOD` and post the result?
