### ISSUE TITLE
pihole-FTL: no process found

### ISSUE THREAD

**Issue by necrogami** [MoJo2600/pihole-kubernetes#223]
So i recently tried installing this via a helm chart 

` helm install my-pihole mojo2600/pihole -values ../k8/pihole.values.yml --version 2.5.8`

This is my values file:

```
dnsmasq:
  customDnsEntries:
    - address=system/town/192.168.18.1

persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.18.20
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.18.20
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
```

When i `kubectl logs my-pihole -f` it keeps spitting this out and repeating. Any idea why?

```
Starting pihole-FTL (no-daemon) as pihole
Stopping pihole-FTL
pihole-FTL: no process found
Starting pihole-FTL (no-daemon) as pihole
Stopping pihole-FTL
pihole-FTL: no process found
```
