### ISSUE TITLE
CNAME entries - error: read-only file system

### ISSUE THREAD

**Issue by krisclarkdev** [MoJo2600/pihole-kubernetes#224]
When adding a CNAME entry using the following values.yaml the web ui reports it has been successful but nothing populates.  When checking the pod logs I get the following error

`/opt/pihole/webpage.sh: line 769: /etc/dnsmasq.d/05-pihole-custom-cname.conf: Read-only file system`

values.yaml

```
replicaCount: 2
strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 1

image:
  repository: "pihole/pihole"
  tag: ""
  pullPolicy: IfNotPresent

dualStack:
  enabled: false

dnsHostPort:
  enabled: false
  port: 53

serviceDns:
  loadBalancerIP: 192.168.6.60
  mixedService: false
  type: LoadBalancer
  port: 53
  externalTrafficPolicy: Local
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceDhcp:
  enabled: false

serviceWeb:
  loadBalancerIP: 192.168.6.60
  http:
    enabled: true
    port: 80

  https:
    enabled: true
    port: 443

  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  loadBalancerIPv6: ""

  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

virtualHost: pihole

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5

resources: {}

persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole-claim"
  accessModes:
    - ReadWriteMany
  size: "50Gi"

nodeSelector: {}
tolerations: []
topologySpreadConstraints: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - k3s-primary

adminPassword: "password"

admin:
  existingSecret: "pihole"
  passwordKey: "password"

extraEnvVars: {}
  # TZ: UTC

extraEnvVarsSecret: {}

DNS1: "1.1.1.1"
DNS2: "1.0.0.1"

antiaff: {}

doh: {}

dnsmasq:
  upstreamServers: []
  customDnsEntries: []
  additionalHostsEntries: []
  staticDhcpEntries: []
  customSettings:
  customCnameEntries: []

adlists: {}
  # If you want to provide blocklists, add them here.
  # - https://hosts-file.net/grm.txt
  # - https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

whitelist: {}
blacklist: {}
regex: {}
ftl: {}

webHttp: "80"
webHttps: "443"
hostname: "pihole"
hostNetwork: "false"
privileged: "false"

customVolumes:
  enabled: false
  config: {}

extraVolumes: {}
extraVolumeMounts: {}
podAnnotations: {}

monitoring:
  podMonitor:
    enabled: false
  sidecar:
    enabled: false
    port: 9617
    image:
      repository: ekofr/pihole-exporter
      tag: 0.0.10
      pullPolicy: IfNotPresent
    resources:
      limits:
        memory: 128Mi

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 1.1.1.1
  - 1.0.0.1
```
