### ISSUE TITLE
FTL failed to start due to failed to create listening socket for port 53: Permission denied

### ISSUE THREAD

**Issue by lknite** [MoJo2600/pihole-kubernetes#225]
In a new kubernetes cluster, 1.23.6, I have deployed pihole using argocd.

Seeing this new error.  Something new need to be set in my values file?

```
pihole:

  serviceDns:
    type: LoadBalancer
    #loadBlancerIP: ""

  admin:
    # -- Specify an existing secret to use as admin password
    existingSecret: "pihole-password"
    # -- Specify the key inside the secret to use
    passwordKey: "password"

  persistentVolumeClaim:
    enabled: true
    storageClass: silver

  serviceDhcp:
    enabled: false

  extraEnvVars:
    TZ: America/Denver
    DNS_BOGUS_PRIV: false
    DNS_FQDN_REQUIRED: false

  DNS1: "10.0.0.2"
  DNS2: "10.0.0.3"

  podDnsConfig:
    enabled: false
```
