### ISSUE TITLE
ServiceWeb not building

### ISSUE THREAD

**Issue by vince-vibin** [MoJo2600/pihole-kubernetes#230]
Hey so im deploying this on my raspberry pi cluster with this comand:
`helm install --version '2.5.8' --namespace pihole --values values.yaml pihole mojo2600/pihole`
but when i check the pods the ServiceWeb pods are not even starting:
```
NAME                      READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
svclb-pihole-web-9nsfv    0/2     Pending   0          3m37s   <none>       <none>        <none>           <none>
svclb-pihole-web-gdllc    0/2     Pending   0          3m37s   <none>       <none>        <none>           <none>
svclb-pihole-web-z2t75    0/2     Pending   0          3m37s   <none>       <none>        <none>           <none>
svclb-pihole-web-xshwc    0/2     Pending   0          3m37s   <none>       <none>        <none>           <none>
svclb-pihole-dhcp-v8gkd   1/1     Running   0          3m37s   10.42.1.9    worker1       <none>           <none>
svclb-pihole-dhcp-5rj2v   1/1     Running   0          3m37s   10.42.0.33   raspberrypi   <none>           <none>
svclb-pihole-dhcp-vnqh5   1/1     Running   0          3m37s   10.42.2.9    worker2       <none>           <none>
svclb-pihole-dhcp-ptmxq   1/1     Running   0          3m37s   10.42.3.9    worker3       <none>           <none>
pihole-5f7b84cfb8-ms4w8   1/1     Running   0          3m37s   10.42.0.35   raspberrypi   <none>           <none>
```
also this is my values.yaml:
```
---
persistentVolumeClaim:
  enabled: true

serviceWeb:
  http:
    enabled: true
    port: 80
  https:
    enabled: true
    port: 443
  type: ClusterIP
  loadBalancerIP: "192.168.178.201"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDNS:
  loadBalancerIP: 192.168.178.202
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDhcp:
  loadBalancerIP: 192.168.178.203
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
```
Do you guys have any idea?
