### ISSUE TITLE
installation using helm3 fails

### ISSUE THREAD

**Issue by runningman84** [MoJo2600/pihole-kubernetes#24]
helm operator reports this error:
```
ts=2020-01-13T20:47:52.764681657Z caller=release.go:217 component=release release=pihole targetNamespace=pihole resource=pihole:helmrelease/pihole helmVersion=v3 error="Helm release failed" revision=49ea46486a904d1b5a491f8d223b7b9c92eacc24 err="failed to upgrade chart for release [pihole]: template: pihole/templates/_helpers.tpl:15:14: executing \"pihole.fullname\" at <.Values.fullnameOverride>: can't evaluate field Values in type string"
```
This is my config
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  releaseName: pihole
  helmVersion: v3
  chart:
    git: git@github.com:MoJo2600/pihole-kubernetes.git
    path: pihole
  values:
    name: pihole
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
      hosts:
         - pihole.example.com
    serviceTCP:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceUDP:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    doh:
      enabled: true
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
```
Does it work for you?

**Comment by MoJo2600** [comment]
I have to test this. did not try it with helm3 yet.

**Comment by henry2man** [comment]
Just my 2 cents, I was able to deploy the chart using a fresh install of k3s + Helm3 over a pair of amd64 nodes. My values.yaml far more simple:

```
persistentVolumeClaim:
  # set to true to use pvc
  enabled: true
  # set to true to use you own pvc
  existingClaim: true

adminPassword: "****************"

# default upstream DNS servers to use
DNS1: "8.8.8.8"
DNS2: "8.8.4.4"

dnsmasq:
  customDnsEntries:
    - address=/host1.local/192.168.0.21
    - address=/host2.local/192.168.0.22

adlists:
  - https://xxxx
  - https://xxxx
  - https://xxxx
```
