### ISSUE TITLE
Can't reliably get DNS resolution with multi-node deployment

### ISSUE THREAD

**Issue by kenlasko** [MoJo2600/pihole-kubernetes#243]
I have a 3-node K3S setup using Traefik for ingress, MetalLB for load balancing and Longhorn for shared storage.  I installed Pihole via the latest MoJo2600 Helm chart with the following additional settings:
```
persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteMany

ingress:
  enabled: true
  hosts:
    - pihole.mydomain.com
  annotations:
    kubernetes.io/ingress.class: traefik

adminPassword: asf982328374jofdshjkl23479r

serviceWeb:
  type: ClusterIP

serviceDns:
  loadBalancerIP: 192.168.1.100
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
  externalTrafficPolicy: Local

serviceTCP:
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
```

DNS resolution only works when the MetalLB speaker pod that is on the same node as the Pihole pod responds to the network request. If I set the **externalTrafficPolicy** to **Cluster**, then it works fine, but then I don't see the originating IP address/hostname. [I posted about this in the Discussion folder along with someone else](https://github.com/MoJo2600/pihole-kubernetes/discussions/233). As far as I know, you can't guarantee which MetalLB speaker pod will respond to an IP address request, which means that running Pihole in a multi-node Kubernetes deployment won't work. At least this is how my current understanding works. Am I doing something fundamentally wrong?  I'm pretty new at this Kubernetes stuff.
