### ISSUE TITLE
K8S with MetalLB - unable to access dns server

### ISSUE THREAD

**Issue by i5Js** [MoJo2600/pihole-kubernetes#252]
Hi, it's very close to the issue [201](https://github.com/MoJo2600/pihole-kubernetes/issues/201). 
Everything was working fine, as usual, but suddenly, now, I always have time out:

```
i5Js@virtsrv:~/K8s/pihole$ nslookup -all -debug -type=ANY -class=ANY www.google.es 192.168.1.116
Default server: 192.168.1.116
Address: 192.168.1.116#53
Default server: 192.168.1.7
Address: 192.168.1.7#53
Default server: 192.168.1.254
Address: 192.168.1.254#53

Set options:
  novc			nodebug		nod2
  search		recurse
  timeout = 0		retry = 3	port = 53	ndots = 1
  querytype = A       	class = IN
  srchlist = noldor.local
;; Connection to 192.168.1.116#53(192.168.1.116) for www.google.es failed: timed out.
;; Connection to 192.168.1.116#53(192.168.1.116) for www.google.es failed: timed out.
;; connection timed out; no servers could be reached

;; Connection to 192.168.1.116#53(192.168.1.116) for www.google.es failed: timed out.
```

I have deployed pihole using helm, with the following values:

```
dnsHostPort:
  # -- set this to true to enable dnsHostPort
  enabled: false
  # -- default port for this pod
  port: 53

# -- Configuration for the DNS service on port 53
serviceDns:

  # -- deploys a mixed (TCP + UDP) Service instead of separate ones
  mixedService: false

  # -- `spec.type` for the DNS Service
  type: LoadBalancer
#  type: NodePort

  # -- The port of the DNS service
  port: 53

  # -- Optional node port for the DNS service
  nodePort: ""

  # -- `spec.externalTrafficPolicy` for the DHCP Service
  externalTrafficPolicy: Local

  # -- A fixed `spec.loadBalancerIP` for the DNS Service
  loadBalancerIP: 192.168.1.116
  # -- A fixed `spec.loadBalancerIP` for the IPv6 DNS Service
  loadBalancerIPv6: ""

  # -- Annotations for the DNS service
  annotations: 
    # metallb.universe.tf/address-pool: network-services
     metallb.universe.tf/allow-shared-ip: pihole-svc
```

And the services come up fine:

```
i5Js@virtsrv:~/K8s/pihole$ k get svc -n dns-home
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                    AGE
pihole-dns-tcp   LoadBalancer   10.97.41.222    192.168.1.116   53:31075/TCP               10m
pihole-dns-udp   LoadBalancer   10.108.8.199    192.168.1.116   53:31289/UDP               10m
pihole-web       ClusterIP      10.110.49.244   <none>          80/TCP,443/TCP,49312/TCP   10m
```

I can access to the web-ui  and work with pihole database. 

I have upgraded metallb to the last version, but it didn't help. 

Any tip to troubleshoot?

Thanks all.
