### ISSUE TITLE
pihole-FTL: no process found

### ISSUE THREAD

**Issue by Rahulsharma0810** [MoJo2600/pihole-kubernetes#271]
Yet Another "pihole-FTL: no process found" 

I tried `pihole/ftl-build:v2.3-alpine` Image, but it's just entering to crashbackLoop, without even starting the container. 

```
replicaCount: 1
nodeSelector:
  kubernetes.io/hostname: kube-node-1-01

image:
  # -- the repostory to pull the image from
  repository: "pihole/pihole"
  # -- the docker tag, if left empty it will get it from the chart's appVersion
  tag: ""
  # -- the pull policy
  pullPolicy: Always

dnsHostPort:
  # -- set this to true to enable dnsHostPort
  enabled: true
  # -- default port for this pod
  port: 53

# -- Configuration for the DNS service on port 53
serviceDns:
  # -- deploys a mixed (TCP + UDP) Service instead of separate ones
  mixedService: true

  # -- `spec.type` for the DNS Service
  type: LoadBalancer

serviceDhcp:
  # -- Generate a Service resource for DHCP traffic
  enabled: true

  # -- `spec.type` for the DHCP Service
  type: LoadBalancer


persistentVolumeClaim:
  # -- set to true to use pvc
  enabled: true

# -- should the container use host network
hostNetwork: "true"

# -- should container run in privileged mode
privileged: "true"
extraEnvVars: { DNSMASQ_USER: "root" }
capabilities:
  add:
    - NET_ADMIN
    - CAP_NET_RAW
    - CAP_NET_ADMIN
    - CAP_SYS_NICE
    - CAP_CHOWN
```

Degrading versions doesn't help. Any guidance is highly appreciated.

**Comment by Rahulsharma0810** [comment]
I found enabling 

```
hostNetwork: true
``` 
Results `pihole-FTL: no process found`

I am trying to make DHCP work by following https://github.com/MoJo2600/pihole-kubernetes/issues/18#issuecomment-556998725

**Comment by Madic-** [comment]
You get the error because there is already some process listening on udp port 57, so pihole can't use it. But I got it working with dhcp enabled. Though it requires the help of a dhcphelper (or dhcp relay).

Basically I'm running pihole as a normal pod, not with host networking enabled. But the dhcphelper is configured as hostonly and forwards the dhcp requests as unicast frames to pihole.

The important values for this chart:

```
      serviceDhcp:
        loadBalancerIP: 192.168.1.232
        type: LoadBalancer
    customSettings:
      - dhcp-option=6,192.168.1.232,192.168.1.1 # DNS dhcp option
      capabilities:
        add:
          - NET_ADMIN
```

This exposes the dhcp service on 192.168.1.232. The following dhcphelper kubernetes deployment forwards the dhcp broadcasts to 192.168.1.232:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dhcphelper
  name: dhcphelper
  namespace: dns
spec:
  selector:
    matchLabels:
      app: dhcphelper
  replicas: 1
  template:
    metadata:
      labels:
        app: dhcphelper
    spec:
      containers:
        - name: dhcphelper
          image: homeall/dhcphelper:latest
          env:
            - name: IP
              value: "192.168.1.232"
            - name: TZ
              value: "Europe/Berlin"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
      hostNetwork: true
  strategy:
    type: Recreate
```
