### ISSUE TITLE
[Question] What is the role of chart ingress?

### ISSUE THREAD

**Issue by magsol** [MoJo2600/pihole-kubernetes#276]
I have pihole-kubernetes running on my home k3s cluster (6x Raspberry Pi 4B). I'm still in the process of configuring [my home network to use Pi Hole as the sole DNS provider](https://discourse.pi-hole.net/t/how-do-i-configure-my-devices-to-use-pi-hole-as-their-dns-server/245), but I'm also still learning the ins and outs of kubernetes and had some questions around the Pi Hole helm configuration, specifically the networking.

For reference, here are the relevant portions of my `values.yaml`:

```yaml
serviceDns:
  mixedService: false
  type: LoadBalancer
  loadBalancerIP: "192.168.4.202"

serviceDhcp:
  enabled: false

serviceWeb:
  http:
    enabled: true
    port: 80

  https:
    enabled: true
    port: 443

  type: LoadBalancer
  loadBalancerIP: "192.168.4.203"

ingress:
  enabled: false

doh:
  enabled: true
```

As far as I can tell, this is working. But I had some questions, in no particular order:

- What role would an ingress resource serve here? Why would I enable one?
- Is there any reason why I'd want to make either `serviceDns` or `serviceWeb` (or both) a `ClusterIP` type, instead of `LoadBalancer`?
- Should `serviceDns` and `serviceWeb` have different `loadBalancerIP` values?

Thank you in advance!
