### ISSUE TITLE
nodePort works for serviceDns but doesn't work for serviceWeb

### ISSUE THREAD

**Issue by lknite** [MoJo2600/pihole-kubernetes#284]
values.yaml
```
serviceWeb:
  type: NodePort
  nodePort: 30080
  https:
    enabled: false
  http:
    enabled: true

serviceDns:
  mixedService: true
  nodePort: 30053
```

results in:
```
service/pihole-dns   NodePort   10.43.171.96   <none>        53:30053/TCP,53:30053/UDP   4m49s
service/pihole-web   NodePort   10.43.27.183   <none>        80:30806/TCP                3m7s
```

see how 30053 is set correctly but 30806 isn't, should be 30080
