### ISSUE TITLE
Feature Request/Discussion: Allow mapping of /etc/pihole/custom.list as a configmap

### ISSUE THREAD

**Issue by andeke07** [MoJo2600/pihole-kubernetes#297]
I have been playing around with GitOps (argocd) and desired state configuration and would like to extend this to my Pihole to be able to configure all my DNS settings in git. In particular, my local DNS names.

Is there a possibility of mounting /etc/pihole/custom.list as a configmap? I noticed if you add a new line to this file directly in the container, the local DNS list will update, so I was hoping I could create that as a configmap which could then update the container's file any time it received an update.

I realise this would mean I could not write to that list from the pihole UI (it would get overwritten by the configmap) but I would be interested to see if I could get this working somehow.

**Comment by laurelmay** [comment]
Does setting values for `customDnsEntries` or `customCnameEntries` fit your needs? Both of these seem to be slightly more flexible than a basic `custom.list` as they can allow multiple values. You can also use `upstreamServers` to specifically redirect hosts under a given domain to a different DNS server. Those all get specified in  And `additionalHostsEntries` can be used for regular `/etc/hosts`-format. The downside with these files is that I don't believe you're able to see the configuration within the Pi-hole UI.

Finally, if you want to put something together for your own config, you can specify `extraObjects`, `extraVolumes`, and `extraVolumeClaims` to create configmap and mount it, but you'll be missing a way to automatically restart the pod when the config map changes (but by specifying `podAnnotations` and manually changing a value you can perhaps work around that). Something along the lines of:

```yaml
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pihole-custom-list
      labels:
        app: {{ template "pihole.name" . }}
        chart: {{ template "pihole.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    data:
      custom.list: |
        # Custom entries go here
podAnnotations:
  custom-list-revision: 1 # Increment each time the list changes
extraVolumeMounts:
  custom-list:
    subPath: custom.list
    mountPath: /etc/pihole/custom.list
extraVolumes:
  custom-list:
    configMap:
      name: pihole-custom-list
```

Note that if you've set `persistentVolumeClaim.enabled=true`, the file from the configmap will take precedence over the file from the PVC; so if you make an edit in the UI or via the Pi-hole API, it will be lost the next time the pod restarts.

**Comment by matthewnbrown** [comment]
This issue is a bit dated, but I had a similar problem. I'm running nebula sync to synchronize my Piholes. The `customDnsEntries` and `customCnameEntries` weren't syncing with nebula. I ended up passing local DNS and CNAME records through the `FTLCONF_dns_hosts` and `FTLCONF_dns_cnameRecords` environment vars as shown below. They show up in the local records through the UI and are synced with nebula-sync.

```yaml
extraEnvVars:
  FTLCONF_dns_hosts: |
    192.168.1.1 domain1.com;
    192.168.1.2 domain2.com;
  FTLCONF_dns_cnameRecords: |
    somesite.com, domain1.com
```
