### ISSUE TITLE
Custom existing PVC name

### ISSUE THREAD

**Issue by henry2man** [MoJo2600/pihole-kubernetes#30]
Please add an extra values.yaml configuration key to set a custom name for the "existing" Persistent Volume Claim. For now the existing PVC must be named "pihole". Also this prevents to have more than one pihole deployment in the same namespace.

Also please consider a refactor of the value keys. For example Bitnami has its own rule-of-thumb for this scenarios:
https://github.com/bitnami/charts/tree/master/upstreamed/redmine/#existing-persistentvolumeclaims

A possible refactor could be:

```
## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  ## OLD: persistentVolumeClaim.enabled
  enabled: true 
  ## A manually manage Persistent Volume Claim
  ## Requires persistence.enable: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  annotations: {}
  ## PiHole data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: "500Mi"
```

What do you think?
