### ISSUE TITLE
Password set with existingSecret not working

### ISSUE THREAD

**Issue by gianmarco-mameli** [MoJo2600/pihole-kubernetes#311]
Hi,
I've deployed this chart on a k3s instance, all works as expected except the admin password configured as external secret.
If I use the value `adminPassword` it works, but with this snippet in the values:
```yaml
  admin:
    enabled: true
    existingSecret: "pihole-password"
```
and the secret configured like this
```bash
Name:         pihole-password
Namespace:    pihole
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  6 bytes
```
doesn't work

What am I doing wrong?
Thanks

**Comment by 1moere1** [comment]
same issue here

**Comment by Robsta86** [comment]
Same issue here. I see the pod has the correct value from the secret set for the environment variable called "WEBPASSWORD", so helm configuration wise things seem to do what they should be doing. 

Maybe a bug in pi-hole?

**Comment by gianmarco-mameli** [comment]
Hi, I made it work, the only difference is that I'm not inserting the secret directly, but it's generated from a third party secret injector (1Password Operator), so I think the difference it's in the encoding of the value.
In the values file I have this config:
```
admin:
  enabled: true
  existingSecret: "pihole-password"
passwordKey: "password"
```

**Comment by polfor** [comment]
Same issue here on chart v2.29.1
I have my secret base64 encoded then using a manifest encrypted with sops (age). When describing the secret its value is correctly decrypted, so kinda clueless.
`admin:
         enabled: true
         existingSecret: pihole-admin-password
         passwordKey: "password"`

**Comment by xalxnder** [comment]
Same issue for me on chart `v2.31.0`.

**Comment by AbdifitahW** [comment]
I'm on the `2.35` chart version. 

```yaml
values:
    admin:
      enabled: true
      existingSecret: "pihole-secret"
      passwordKey: "password"
```

Checking the `env` variables there seems to be some trailing whitespace following the `FTLCONF_webserver_api_password` that might be the issue.

```
FTLCONF_dns_listeningMode=all
KUBE_DNS_PORT_9153_TCP_ADDR=10.96.0.10
FTLCONF_webserver_api_password='redacted'

PIHOLE_DHCP_PORT_67_UDP_PORT=67
PIHOLE_DHCP_PORT_67_UDP_PROTO=udp
KUBE_DNS_PORT_9153_TCP_PORT=9153
```
