### ISSUE TITLE
Pi-Hole API as default startup probe

### ISSUE THREAD

**Issue by Javex** [MoJo2600/pihole-kubernetes#344]
If you provide an invalid Pi-Hole configuration such that the web interface starts, but e.g. FTL doesn't, then the current readiness & liveness probes don't detect this. However, Pi-Hole offers an API that can be used to probe a bit more thoroughly. The current Helm chart already supports configuring this, but I would suggest this should be the default.

Here's the configuration I just applied (ignore the changed timeouts):

```
probes:
  liveness:
    type: command
    command:
      - /bin/sh
      - -c
      - "curl --silent http://localhost/api/info/login | jq 'if (.dns | not) then halt_error(1) end'"
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    type: command
    command:
      - /bin/sh
      - -c
      - "curl --silent http://localhost/api/info/login | jq 'if (.dns | not) then halt_error(1) end'"
    enabled: true
    initialDelaySeconds: 5
    failureThreshold: 5
    timeoutSeconds: 5
```

This only works on Pi-Hole v6 (i.e. I'm running the version in https://github.com/MoJo2600/pihole-kubernetes/pull/343). While v5 supports a similar API call, I don't think it's worth building given we should be upgrading to v6 anyway.

When querying `http://localhost/api/info/login` it returns the following values:

```json
{
  "dns": true,
  "https_port": 443,
  "took": 0.00000977516174316406
}
```

If FTL is not running `dns` will be `false`. The `jq` command checks this and returns with exit code `1`, failing the check.

An example for how to reproduce such a condition is to enable DHCP, but then fail to provide `CAP_NET_RAW`. These variables will do the trick (in v6). Note that I needed to set a range, just marking it active didn't start DHCP.

```yaml
extraEnvVars:
  FTLCONF_dhcp_active: "true"
  FTLCONF_dhcp_start: "10.0.0.2"
  FTLCONF_dhcp_end: "10.0.0.254"
  FTLCONF_dhcp_router: "10.0.0.1"
```

When this is applied without the right capability, it fails to start FTL but the web interface will be up.

Happy to make a PR if you're interested, but there might be reason why it's not the default so thought I'd check first.
