### ISSUE TITLE
customCnameEntries not working

### ISSUE THREAD

**Issue by Thorsten2605** [MoJo2600/pihole-kubernetes#348]
I configured my release.yaml this way:

```
    dnsmasq:
      customSettings: |
        local-service=0
      customDnsEntries:
        - address=/traefik.XXX.com/172.20.10.100
      customCnameEntries:
        - cname=wiki.XXX.com,traefik.XXX.com
        - cname=pihole.XXX.com,traefik.XXX.com
```
(XXX only for invisible domain-name)

But if I do a nslookup on wiki.XXX.com I don't get the IP address of traefik.XXX.com.

Is there anything wrong placed in the dnsmasq-config?
