### ISSUE TITLE
Does not Expose on port 53

### ISSUE THREAD

**Issue by darknite12** [MoJo2600/pihole-kubernetes#52]
Hello, I don't know if this is the right channel for support/help. But here it goes. Everything works great with the configurations i have got. The only thing is that the ports (ie. 53, 80) are exposed on random ports. I guess i can live with port 80 living on any random port as this is only the admin portal. But in order for me to point my router to pihole using the router's dns setting, the port on the Kubernetes node that is exposed must be 53

```NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                   AGE
service/pihole-tcp   LoadBalancer   10.110.201.40    <pending>     80:30181/TCP,443:31614/TCP,53:30634/TCP   2m46s
service/pihole-udp   LoadBalancer   10.110.195.142   <pending>     53:30699/UDP,67:30840/UDP                 2m46s
```
As you can see from above port 53 on TCP is assigned external port 30634. How do I make it so that port 53 is mapped to port 53.

Thank you

**Comment by i5Js** [comment]
Please, could you share your service configuration?
`kubectl get svc -n <namespace`

**Comment by MoJo2600** [comment]
Hi, i think you read the information here the wrong way round. Kubernetes is trying to create a Loadbalancer but it is not yet created (status is <pending>). The information you see is, that port 80 in the Loadbalancer will be forwarded to port 30181 on the pod. 
My services look like this:
```
pihole-tcp                                               LoadBalancer   10.110.191.202   192.168.178.252   80:30758/TCP,443:30402/TCP,53:30465/TCP   109d
pihole-udp                                               LoadBalancer   10.99.37.68      192.168.178.252   53:30029/UDP,67:30037/UDP                 109d
```
You can see, that a Loadbalancer has been created on IP 192.168.178.252 and it exposes the ports 80,443,53 TCP and 53,67 UDP on this IP. 

You can do a `kubectl describe svc pihole-tcp` to see why your Loadbalancer is still pending.

**Comment by darknite12** [comment]
Thank you for replying. I just want to start by saying I am a total Noob. Just wanted to get that out of the way.

The reason why I mention that port 53 on TCP is assigned external port 30634 is because port 80 on TCP seems to be assigned to 30181 because when I point my browser over to http://node-ip:30181/admin I get the pihole admin. I can login etc.

when i do a `kubectl describe svc pihole-tcp -n pihole` i get the following

```
Name:                     pihole-tcp
Namespace:                pihole
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-1.7.7
                          heritage=Helm
                          release=pihole
Annotations:              meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: pihole
                          metallb.universe.tf/allow-shared-ip: pihole-svc
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP:                       10.102.123.43
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30804/TCP
Endpoints:                192.168.205.227:8000
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30105/TCP
Endpoints:                192.168.205.227:443
Port:                     dns  53/TCP
TargetPort:               dns/TCP
NodePort:                 dns  32089/TCP
Endpoints:                192.168.205.227:53
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30299
Events:                   <none>
```
when i do a `kubectl get svc -n pihole` i get
```
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                   AGE
pihole-tcp   LoadBalancer   10.102.123.43   <pending>     80:30804/TCP,443:30105/TCP,53:32089/TCP   6m1s
pihole-udp   LoadBalancer   10.105.93.11    <pending>     53:31834/UDP,67:30489/UDP                 6m1s
```

as you can see they are still pending. When i do `kubectl get ingress -n pihole` i get

```
NAME     CLASS    HOSTS               ADDRESS   PORTS   AGE
pihole   <none>   kubenode1,pi.hole             80      7m8s
```
lastly when i do `kubectl describe ingress pihole -n pihole` i get
```
Name:             pihole
Namespace:        pihole
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  kubenode1
              /   pihole-tcp:http (192.168.205.227:8000)
  pi.hole
              /   pihole-tcp:http (192.168.205.227:8000)
Annotations:  kubernetes.io/ingress.class: nginx
              meta.helm.sh/release-name: pihole
              meta.helm.sh/release-namespace: pihole
Events:       <none>
```

my pihole.values.yaml

```
replicaCount: 1

image:
  repository: "pihole/pihole"
  tag: v5.0
  pullPolicy: IfNotPresent

serviceTCP:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

virtualHost: pi.hole

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - kubenode1
  tls: []
  
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    initialDelaySeconds: 60
    failureThreshold: 3
    timeoutSeconds: 5

resources: {}

persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole"
  annotations: {}

  accessModes:
    - ReadWriteOnce
  size: "500Mi"

nodeSelector: {}

tolerations: []

affinity: {}

adminPassword: "admin"

admin:
  existingSecret: ""
  passwordKey: "password"

extraEnvVars:
  TZ: America/New_York

extraEnvVarsSecret: {}

DNS1: "8.8.8.8"
DNS2: "8.8.4.4"

doh:
  enabled: false
  name: "cloudflared"
  repository: "crazymax/cloudflared"
  tag: latest
  pullPolicy: IfNotPresent

dnsmasq:
  upstreamServers: []

  customDnsEntries: []

  additionalHostsEntries: []

adlists: {}

whitelist: {}

blacklist: {}

regex: {}

webHttp: "8000"
webHttps: "443"
hostNetwork: "false"
privileged: "false"
```

I have also done it with 
```
serviceTCP:
  type: NodePort
```
but i still get the exact same behaviour (ie. i hit the pihole admin with my browser through port 30181) however when i do a `kubectl get svc -n pihole` i get

```
NAME                 TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)                                   AGE
service/pihole-tcp   NodePort   10.111.178.124   <none>        80:31273/TCP,443:31995/TCP,53:31250/TCP   8s
service/pihole-udp   NodePort   10.103.71.80     <none>        53:30707/UDP,67:30835/UDP                 8s
```
Notice that the external-ip says <none>

Once again thank you for taking the time.

**Comment by i5Js** [comment]
Hi, 

Did you configure metallb? Could you please share the config map?
` kubectl describe cm <name>-n <namespace>`

It seems It's waiting for an IP to assign the services.

**Comment by darknite12** [comment]
No I haven't configured it but as I mentioned before when I configure pihole without a load balancer it still does not expose pihole on the desired ports.

Ideally what I want is to expose port 53 because that is what the DNS clients (ie. My router) will talk to.

**Comment by i5Js** [comment]
The internal ports are ok, mine are same than @MoJo2600 
If you want to configure the service using a LoadBalancer, you need to configure metallb or traefik.

**Comment by darknite12** [comment]
Is it possible to set it up without a load balancer?

**Comment by i5Js** [comment]
Yes, you can change from LoadBalancer to NodePort.

**Comment by darknite12** [comment]
I did as well. But the same sort of thing happens. See, the big comment at the very bottom I describe what happens when I use NodePort... basically the same thing happens the ports are not 53 and 80 but 32something

**Comment by MoJo2600** [comment]
I think with Nodeport you will always have a problem with port 53. This is used by systemd most of the time. I'd recommend to go with metallb and use a Loadbalancer. Setting up metallb is very easy. 

I created a `values.yml` for my helm deployment like this:

```
configInline:
  address-pools:
  - addresses:
    - 192.168.178.60-192.168.178.80
    name: default
    protocol: layer2
  - addresses:
    - 192.168.178.245-192.168.178.254
    name: network-services
    protocol: layer2
```

Then i did my deployment with this values.yml: `helm install --name metallb -f values.yml stable/metallb` 

And if you annotate your services like this, you'll have pihole running on `.252` with an exposed port 53.:

``` 
serviceTCP:
  loadBalancerIP: 192.168.178.252
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceUDP:
  loadBalancerIP: 192.168.178.252
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
```

**Comment by darknite12** [comment]
I did as you described and when i run `kubectl get all -n pihole` i get
```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/metallb-controller-6655c976c5-cvl6w   1/1     Running   0          14m
pod/metallb-speaker-dbjqn                 1/1     Running   0          14m
pod/metallb-speaker-nxflq                 1/1     Running   0          14m
pod/pihole-56d95c7cf5-t5q87               1/1     Running   0          72s

NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                                   AGE
service/pihole-tcp   LoadBalancer   10.101.115.124   192.168.178.252   80:31497/TCP,443:32013/TCP,53:30073/TCP   72s
service/pihole-udp   LoadBalancer   10.105.234.180   192.168.178.252   53:32051/UDP,67:32194/UDP                 72s

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/metallb-speaker   2         2         2       2            2           beta.kubernetes.io/os=linux   14m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-controller   1/1     1            1           14m
deployment.apps/pihole               1/1     1            1           72s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-controller-6655c976c5   1         1         1       14m
replicaset.apps/pihole-56d95c7cf5               1         1         1       72s
```
So now, how do I access the Admin portal and more importantly what address do I use in my router's DNS config?

**Comment by darknite12** [comment]
I got it working! I think the problem was that the LoadBanlencer IP address I was using was not something my router was allowing. My loadBalancer IP is as follows `loadBalancerIP: 192.168.1.252` and in the metallb configuration looks like this
```
configInline:
  address-pools:
  - addresses:
    - 192.168.1.60-192.168.1.80
    name: default
    protocol: layer2
  - addresses:
    - 192.168.1.245-192.168.1.254
    name: network-services
    protocol: layer2
```
notice the IP range....so now when i run `kubectl get all -n pihole`
```
NAME                                      READY   STATUS    RESTARTS   AGE
pod/metallb-controller-6655c976c5-htttw   1/1     Running   0          2m22s
pod/metallb-speaker-c7ngp                 1/1     Running   0          2m22s
pod/metallb-speaker-qmn8b                 1/1     Running   0          2m22s
pod/pihole-56d95c7cf5-c7swb               1/1     Running   0          117s

NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                   AGE
service/pihole-tcp   LoadBalancer   10.101.94.141   192.168.1.252   80:30110/TCP,443:30099/TCP,53:31327/TCP   117s
service/pihole-udp   LoadBalancer   10.103.69.248   192.168.1.252   53:30547/UDP,67:32427/UDP                 117s

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/metallb-speaker   2         2         2       2            2           beta.kubernetes.io/os=linux   2m22s

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-controller   1/1     1            1           2m22s
deployment.apps/pihole               1/1     1            1           117s

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-controller-6655c976c5   1         1         1       2m22s
replicaset.apps/pihole-56d95c7cf5               1         1         1       117s
```
Now when i point my browser to http://192.168.1.252/admin i get the Pihole admin. Thank you all for your help and guidance.
