### ISSUE TITLE
ingress templating is too cute

### ISSUE THREAD

**Issue by jetersen** [MoJo2600/pihole-kubernetes#56]
The ingress templating is trying to be too fancy with appending virtualHost.

I'd like to have a single host ingress.
As it would be impossible to get a let's encrypt certificate for pi.hole

```
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  enabled: true
  hosts:
  - pihole.lan.jetersen.dev
  tls:
  - secret: pihole.lan.jetersen.dev-tls
    hosts:
    - pihole.lan.jetersen.dev

virtualHost: pihole.lan.jetersen.dev
```

becomes:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
  labels:
    app: pihole
    chart: pihole-1.7.7
    release: pihole
    heritage: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - "pihole.lan.jetersen.dev"
        - "pihole.lan.jetersen.dev"
      secretName:
  rules:
    - host: "pihole.lan.jetersen.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-tcp
              servicePort: http
    - host: "pihole.lan.jetersen.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-tcp
              servicePort: http
```

**Comment by MoJo2600** [comment]
Sorry, i don't completely understand what has to be changed. I'm not too familiar with ingresses,

**Comment by jetersen** [comment]
I use cert-manager to inject certificates.
Generating a certificate for pi.hole would be impossible if I used the default virtualHost.
So I must change the default.

With the current templating it would try and include the virtualHost into the rules but not TLS
and if I only enable ingress.
The default `host` is suddenly included but no TLS

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole
  labels:
    app: pihole
    chart: pihole-1.7.7
    release: pihole
    heritage: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-tcp
              servicePort: http
    - host: "pihole.lan.jetersen.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-tcp
              servicePort: http
```

Basically I am fighting with the odd templating of default and appending

**Comment by jetersen** [comment]
Looking at for instance prometheus-operator they handle it safely.

```
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
    - prometheus.jetersen.dev
    tls:
    - hosts:
      - prometheus.jetersen.dev
      secretName: prometheus.jetersen.dev-tls
```
