### ISSUE TITLE
PiHole not reachable after 2-3 hours

### ISSUE THREAD

**Issue by mikebell** [MoJo2600/pihole-kubernetes#58]
I'm running the latest version of the chart on microk8s. Here are my values:

```
persistentVolumeClaim:
    enabled: true
  
serviceTCP:
    loadBalancerIP: 192.168.1.101
    annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer
  
serviceUDP:
    loadBalancerIP: 192.168.1.101
    annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer
```

When I install the chart everything works fine and I can see the admin page on http://192.168.1.101/admin after 2-3 hours it becomes unreachable.

Running:

`k -n pihole rollout restart deployment pihole`

Brings the application back up again.

I'm aware that this might not even be an issue with this chart but I'd really appreciate any tips on how to debug it. I'll grab the logs from the pod when it falls over again but I didn't see anything wrong the first time around.
