### ISSUE TITLE
can't change sharing key for "pihole/pihole-tcp", address also in use by pihole/pihole-udp

### ISSUE THREAD

**Issue by craigjmidwinter** [MoJo2600/pihole-kubernetes#59]
For some reason, I can't seem to colocate the tcp/udp services. Says there is an issue with the sharing key.

```
~/workspace/kubernetes 
❯ kubectl describe svc pihole-udp --namespace pihole
Name:                     pihole-udp
Namespace:                pihole
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-1.7.8
                          heritage=Helm
                          release=pihole
Annotations:              meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: pihole
                          metallb.universe.tf/allow-shared-ip: pihole
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP:                       10.97.203.194
IP:                       192.168.0.230
LoadBalancer Ingress:     192.168.0.230
Port:                     dns-udp  53/UDP
TargetPort:               dns-udp/UDP
NodePort:                 dns-udp  32314/UDP
Endpoints:                10.244.1.26:53
Port:                     client-udp  67/UDP
TargetPort:               client-udp/UDP
NodePort:                 client-udp  30298/UDP
Endpoints:                10.244.1.26:67
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30674
Events:
  Type    Reason        Age    From                Message
  ----    ------        ----   ----                -------
  Normal  IPAllocated   3m41s  metallb-controller  Assigned IP "192.168.0.230"
  Normal  nodeAssigned  2m33s  metallb-speaker     announcing from node "hivemind-2"

~/workspace/kubernetes 
❯ kubectl describe svc pihole-tcp --namespace pihole
Name:                     pihole-tcp
Namespace:                pihole
Labels:                   app=pihole
                          app.kubernetes.io/managed-by=Helm
                          chart=pihole-1.7.8
                          heritage=Helm
                          release=pihole
Annotations:              meta.helm.sh/release-name: pihole
                          meta.helm.sh/release-namespace: pihole
                          metallb.universe.tf/allow-shared-ip: pihole
Selector:                 app=pihole,release=pihole
Type:                     LoadBalancer
IP:                       10.108.117.207
IP:                       192.168.0.230
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  32092/TCP
Endpoints:                10.244.1.26:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  31429/TCP
Endpoints:                10.244.1.26:443
Port:                     dns  53/TCP
TargetPort:               dns/TCP
NodePort:                 dns  32296/TCP
Endpoints:                10.244.1.26:53
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason            Age                    From                Message
  ----     ------            ----                   ----                -------
  Warning  AllocationFailed  3m21s (x2 over 3m44s)  metallb-controller  Failed to allocate IP for "pihole/pihole-tcp": can't change sharing key for "pihole/pihole-tcp", address also in use by pihole/pihole-udp
```

Relevant values.yaml:
```
serviceTCP:                                                                                                                                                                                                                             
  loadBalancerIP: 192.168.0.230                                                                                                                                                                                                         
  annotations:                                                                                                                                                                                                                          
    metallb.universe.tf/allow-shared-ip: pihole                                                                                                                                                                                         
  type: LoadBalancer                                                                                                                                                                                                                    
                                                                                                                                                                                                                                        
serviceUDP:                                                                                                                                                                                                                             
  loadBalancerIP: 192.168.0.230                                                                                                                                                                                                         
  annotations:                                                                                                                                                                                                                          
    metallb.universe.tf/allow-shared-ip: pihole                                                                                                                                                                                         
  type: LoadBalancer                                                                                                                                                                                                                    
```
