### ISSUE TITLE
exposing metrics through service

### ISSUE THREAD

**Issue by Rahulsharma0810** [MoJo2600/pihole-kubernetes#84]
Currently, if metics needed to be scraped,  below conf work, which included pod IP.

```
    additionalScrapeConfigs:
    - job_name: 'pihole'
      static_configs:
        - targets: ['10.244.0.196:9617']
```

```
NAME                          READY   STATUS    RESTARTS   AGE     IP             NODE
pod/pihole-77875bf5f4-w4jvj   2/2     Running   1          7h40m   10.244.0.196 
```

But the pod IP can be easily changed on different events, it's better to create SVC for it so the IP will be static.
