### ISSUE TITLE
Configuration Help

### ISSUE THREAD

**Issue by wrender** [MoJo2600/pihole-kubernetes#85]
Thanks for the helm chart. I'm having an issue and looking for some basic help.  I have a single centos 8/kubernetes host for testing so no external load balancer. I have the following set (below) but the host doesn't seem to forward DNS requests from my test network to it to the pihole NodeIP ports for dns tcp and udp:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  path: /
  hosts:
    - pi.hole.mydomainlocal

persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole"
```

Then on firewalld I forward ports like:
```
sudo firewall-cmd --zone="trusted" --add-forward-port=port=53:proto=udp:toport=31111
sudo firewall-cmd --zone="trusted" --add-forward-port=port=53:proto=tcp:toport=31112
sudo firewall-cmd --zone="public" --add-forward-port=port=53:proto=udp:toport=31111
sudo firewall-cmd --zone="public" --add-forward-port=port=53:proto=tcp:toport=31112
```
