### ISSUE TITLE
Conditional DNS isn't working

### ISSUE THREAD

**Issue by kbreit** [MoJo2600/pihole-kubernetes#87]
I enabled conditional DNS forwarding and it seems to create the file `02-custom.conf` properly. However, when I logged into the PiHole interface the checkbox for "Conditional Forwarding" wasn't enabled. I set it manually using the web interface and found it added the `server=` entry to `01-pihole.conf` instead of `02-custom.conf`.

**Comment by MoJo2600** [comment]
Can you provide your configuration?

**Comment by radicand** [comment]
I use conditional forwarding just fine with this repo, enabled via the extraEnvVars option:

```yaml
extraEnvVars:
  CONDITIONAL_FORWARDING: "true"
  CONDITIONAL_FORWARDING_IP: "192.168.1.1"
  CONDITIONAL_FORWARDING_DOMAIN: "intranet.mydomain.net"
  CONDITIONAL_FORWARDING_REVERSE: "1.168.192.in-addr.arpa"
```

How are you enabling it for your use-case?

**Comment by sam-kleiner** [comment]
@kbreit It looks like pihole [deprecated those old env vars](https://github.com/pi-hole/docker-pi-hole#deprecated-environment-variables), if they aren't working I would try the [new ones](https://github.com/pi-hole/docker-pi-hole#environment-variables). Note `CONDITIONAL_FORWARDING_REVERSE` was replaced with `REV_SERVER_CIDR` and has a different format. I tested and reverse lookups still work. My current config:

```yaml
extraEnvVars:
  REV_SERVER: true
  REV_SERVER_TARGET: 192.168.1.1
  REV_SERVER_DOMAIN: intranet.mydomain.net
  REV_SERVER_CIDR: 192.168.1.0/24
```
